### PR TITLE
Moving Publishing API to backend

### PR DESCRIPTION
**Pull request by ShekharGupta1988**
For now, I haven't removed the publishing API from applens backend. Just keeping it as a safeguard for now. 
And also this :)
image

### CODE REVIEW

**Review by stevenernst131 — APPROVED** [review]
And published by alias, thats great!

**Comment by cindylovescoding** [comment]
This looks good Shekhar:) 
Just curious, can we also click the backdrop or escape button to cancel this modal as well?

**Comment by ShekharGupta1988** [comment]
Correct. You will be able to dismiss the modal.

**Review by cindylovescoding — APPROVED** [review]

**Comment by ShekharGupta1988** [comment]
I'll merge this after the MSFTINT deployment is completed

**Pull request merged**
